services:

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    depends_on:
      - mongo
      - rabbitmq
    env_file:
      - ./consumer/.env
    ports:
      - "${CONSUMER_PORT}:5000"
    networks:
      - iot-network

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    depends_on:
      - mongo
      - rabbitmq
    env_file:
      - ./producer/.env
    ports:
      - "${PRODUCER_PORT}:4000"
    networks:
      - iot-network

  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      - iot-network

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - iot-network
  
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASS}
    depends_on:
      - mongo
    networks:
      - iot-network

volumes:
  mongo-data:

networks:
  iot-network:
    driver: bridge